import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PortfolioService {

  getPortfolio() {
    return [
      {
        id           :36,
        photo        : "./assets/img/projects/registration-form-design.jpg",
        title        : "Componente de introducción con solución de formulario de registro",
        skill        : ["Angular"],
        description  : "Este desafío se elaboró con Angular. Diseño Responsivo. Los usuarios recibiran un mensaje de error cuando se envíe el formulario si: 1) Cualquier campo de entrada está vacío. 2) La dirección de correo electrónico no tiene el formato correcto.",
        date_project : "15/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/intro-component-angular.github.io",
        link_website : "https://roraima1986.github.io/intro-component-angular.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :35,
        photo        : "./assets/img/projects/base-apparel-design.jpg",
        title        : "Ropa Básica",
        skill        : ["Angular"],
        description  : "Este desafío se elaboró con Angular. Diseño Responsivo. Los usuarios recibiran un mensaje de error cuando se envíe el formulario si: 1) El campo de entrada está vacío. 2) La dirección de correo electrónico no tiene el formato correcto",
        date_project : "15/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/base-apparel-angular.github.io",
        link_website : "https://roraima1986.github.io/base-apparel-angular.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           : 34,
        photo        : "./assets/img/projects/interactive-rating-component-design.jpg",
        title        : "Calificación Interactiva",
        skill        : ["Angular"],
        description  : "Este desafío se elaboró con Angular. Diseño Responsivo. Los usuarios seleccionaran y enviaran una calificación numérica, seguidamente verán el estado de la tarjeta 'Gracias' después de enviar una calificación.",
        date_project : "10/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/interactive-rating-angular.github.io",
        link_website : "https://roraima1986.github.io/interactive-rating-angular.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           : 33,
        photo        : "./assets/img/projects/age-calculator-design.jpg",
        title        : "Calculadora de Edad",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Desafío realizado en HTML, CSS y JavaScript. Diseño Responsivo. Los usuarios verán la edad en años, meses y días después de enviar una fecha válida a través del formulario. Se recibirán mensajes de error en los siguientes casos: 1) Cualquier campo esté vacío cuando se envía el formulario. 2) El número de día no está entre 1 y 31. 3) El número de mes no está entre 1 y 12. 4) El año está en el futuro. 5) La fecha no es válida, p. 31/04/1991 (hay 30 días en abril).",
        date_project : "11/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/age-calculator.github.io",
        link_website : "https://roraima1986.github.io/age-calculator.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :32,
        photo        : "./assets/img/projects/newsletter-design.jpg",
        title        : "Formulario de suscripción al boletín con mensaje de éxito",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Desafío realizado en HTML, CSS y JavaScript. Diseño Responsivo. Los usuarios agregarán su correo electrónico y enviarán el formulario. Se verá un mensaje de éxito con su correo electrónico después de enviar correctamente el formulario. Se recibirán mensajes de error en los siguientes casos: 1) El campo esté vacío. 2) La dirección de correo electrónico no tiene el formato correcto.",
        date_project : "07/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/newsletter.github.io",
        link_website : "https://roraima1986.github.io/newsletter.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :31,
        photo        : "./assets/img/projects/huddle-landing-page-design.jpg",
        title        : "Página de inicio de reunión",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "06/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/huddle-landing-page.github.io",
        link_website : "https://roraima1986.github.io/huddle-landing-page.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :30,
        photo        : "./assets/img/projects/ping-coming-soon-page-design.jpg",
        title        : "Página de proximamente",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Desafío realizado en HTML, CSS y JavaScript. Diseño Responsivo. Los usuarios enviarán su correo electrónico. Recibirán un mensaje de error cuando se envíe el formulario si: 1) El campo de entrada está vacío. 2) La dirección de correo electrónico no tiene el formato correcto.",
        date_project : "06/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/ping-coming-soon.github.io",
        link_website : "https://roraima1986.github.io/ping-coming-soon.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :29,
        photo        : "./assets/img/projects/single-price-design.jpg",
        title        : "Grid de Precio Único",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "05/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/single-price.github.io-",
        link_website : "https://roraima1986.github.io/single-price.github.io-/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :28,
        photo        : "./assets/img/projects/registration-form-design.jpg",
        title        : "Componente de introducción con solución de formulario de registro",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Este desafío se elaboró con HTML, CSS y JavaScript. Diseño Responsivo. Los usuarios recibiran un mensaje de error cuando se envíe el formulario si: 1) Cualquier campo de entrada está vacío. 2) La dirección de correo electrónico no tiene el formato correcto.",
        date_project : "05/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/registration-form.github.io",
        link_website : "https://roraima1986.github.io/registration-form.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :27,
        photo        : "./assets/img/projects/base-apparel-design.jpg",
        title        : "Base Apparel",
        skill        : ["HTML5", "CSS3", "JavaScript"],
        date_project : "04/02/2024",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/base-apparel.github.io",
        link_website : "https://roraima1986.github.io/base-apparel.github.io/",
        is_active    :  false,
        is_destacad  : false,
      },
      {
        id           :26,
        photo        : "./assets/img/projects/web-design-layout.jpg",
        title        : "Sitio Web de Videojuegos",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Maquetacion de sitio web realizado solo con HTML y CSS de un portal de noticias para gamer. Diseño Responsivo.",
        date_project : "01/02/2024",
        observation  : "Master en CSS3 Avanzado",
        link_github  : "https://github.com/roraima1986/video-games-new.github.io",
        link_website : "https://roraima1986.github.io/video-games-new.github.io/",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :25,
        photo        : "./assets/img/projects/movies-design.jpg",
        title        : "Películas",
        skill        : ["React"],
        description  : "Maquetacion básica de un portal de películas realizado en React. Diseño Responsivo.",
        date_project : "24/01/2024",
        observation  : "Master en React",
        link_github  : "https://github.com/roraima1986/movies-react.github.io",
        link_website : "https://roraima1986.github.io/movies-react.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :24,
        photo        : "./assets/img/projects/develop-design.jpg",
        title        : "Agencia de Diseño y Desarrollo Web",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Maquetacion de sitio web realizado solo con HTML y CSS de una Agencia de Diseño y Desarrollo Web. Diseño Responsivo.",
        date_project : "21/01/2024",
        observation  : "Master CSS3 Avanzado",
        link_github  : "https://github.com/roraima1986/web-development.github.io",
        link_website : "https://roraima1986.github.io/web-development.github.io/",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :23,
        photo        : "./assets/img/projects/four-card-feature-section-design.jpg",
        title        : "Sección de funciones de cuatro tarjetas",
        skill        : ["React"],
        description  : "Desafío realizado en React. Diseño Responsivo. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "21/11/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/four-card-feature-section.github.io",
        link_website : "https://roraima1986.github.io/four-card-feature-section.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :22,
        photo        : "./assets/img/projects/article-preview-design.jpg",
        title        : "Diseño de vista previa del artículo",
        skill        : ["Angular"],
        description  : "Desafío realizado en Angular. Diseño Responsivo. El usuario podrá ver los enlaces para compartir en las redes sociales cuando hacen clic en el ícono de compartir.",
        date_project : "17/11/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/article-preview.github.io",
        link_website : "https://roraima1986.github.io/article-preview.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :21,
        photo        : "./assets/img/projects/social-proof-design.jpg",
        title        : "Sección de prueba social",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. Diseño Responsivo. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "16/11/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/social-proof.github.io",
        link_website : "https://roraima1986.github.io/social-proof.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :20,
        photo        : "./assets/img/projects/portfolio2-design.jpg",
        title        : "Página de Portafolio",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Maquetacion de sitio web realizado solo con HTML y CSS de una Página de. Diseño Responsivo.",
        date_project : "10/11/2023",
        observation  : "Master CSS3 Avanzado",
        link_github  : "https://github.com/roraima1986/portfolio-design.github.io",
        link_website : "https://roraima1986.github.io/portfolio-design.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :19,
        photo        : "./assets/img/projects/faq-accordion-design.jpg",
        title        : "FAQ accordion card",
        skill        : ["HTML5", "CSS3", "JavaScript"],
        date_project : "03/11/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/faq-accordion.github.io",
        link_website : "https://roraima1986.github.io/faq-accordion.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :18,
        photo        : "./assets/img/projects/profile-card-design.jpg",
        title        : "Profile card component",
        skill        : ["HTML5", "CSS3"],
        date_project : "29/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/profile-card.github.io",
        link_website : "https://roraima1986.github.io/profile-card.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :17,
        photo        : "./assets/img/projects/column-preview-card-design.jpg",
        title        : "Componente de tarjeta de vista previa de 3 columnas",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "25/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/column-preview-card.github.io",
        link_website : "https://roraima1986.github.io/column-preview-card.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :16,
        photo        : "./assets/img/projects/stats-preview-design.jpg",
        title        : "Stats preview card component",
        skill        : ["HTML5", "CSS3"],
        date_project : "24/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/stats-preview-card.github.io",
        link_website : "https://roraima1986.github.io/stats-preview-card.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :15,
        photo        : "./assets/img/projects/order-summary-card-design.jpg",
        title        : "Tarjeta de resumen del pedido",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "16/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/order-summary-card.github.io",
        link_website : "https://roraima1986.github.io/order-summary-card.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :14,
        photo        : "./assets/img/projects/nft-preview-card-design.jpg",
        title        : "Tarjeta de vista previa de NFT",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "13/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/nft-preview-card.github.io",
        link_website : "https://roraima1986.github.io/nft-preview-card.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :13,
        photo        : "./assets/img/projects/interactive-rating-component-design.jpg",
        title        : "Calificación Interactiva",
        skill        : ["HTML", "CSS", "JavaScript"],
        description  : "Este desafío se elaboró en HTML, CSS y JavaScript. Diseño Responsivo. Los usuarios seleccionaran y enviaran una calificación numérica, seguidamente verán el estado de la tarjeta 'Gracias' después de enviar una calificación.",
        date_project : "10/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/interactive-rating.github.io",
        link_website : "https://roraima1986.github.io/interactive-rating.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :12,
        photo        : "./assets/img/projects/product-preview-card-design.jpg",
        title        : "Tarjeta de vista previa del producto",
        skill        : ["HTML", "CSS"],
        description  : "Desafío realizado en HTML y CSS. El usuario podrá ver el diseño óptimo de la página según el tamaño de pantalla de su dispositivo.",
        date_project : "05/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/productcard.github.io",
        link_website : "https://roraima1986.github.io/productcard.github.io/",
        is_active    : true,
        is_destacad  : false,
      },
      {
        id           :11,
        photo        : "./assets/img/projects/results-summary-design.jpg",
        title        : "Results summary",
        skill        : ["HTML5", "CSS3"],
        date_project : "03/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/resultssummary.github.io",
        link_website : "https://roraima1986.github.io/resultssummary.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :10,
        photo        : "./assets/img/projects/code-qr-design.jpg",
        title        : "QR code",
        skill        : ["HTML5", "CSS3"],
        date_project : "01/10/2023",
        observation  : "Desafio de Frontend Mentor",
        link_github  : "https://github.com/roraima1986/qrcode.github.io",
        link_website : "https://roraima1986.github.io/qrcode.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :9,
        photo        : "./assets/img/projects/portafolio-design.jpg",
        title        : "Mi Portafolio",
        skill        : ["Angular"],
        description  : "Página web de mi portafolio, donde muestro mis proyectos, practicas y habilidades. El diseño de la página es responsivo y fue creado usando el framework de Angular.",
        date_project : "05/10/2023",
        observation  : "Propia",
        link_github  : "https://github.com/roraima1986/portafolio",
        link_website : "",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :8,
        photo        : "./assets/img/projects/country-app-design.jpg",
        title        : "Aplicación de países",
        skill        : ["Angular", "Bootstrap"],
        description  : "Plataforma de búsqueda de países por su capital, nombre y región. Desarrollada utilizando Angular y una API Rest.",
        date_project : "01/08/2023",
        observation  : "",
        link_github  : "https://github.com/roraima1986/country-app",
        link_website : "https://roraima1986.github.io/country-app/",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :7,
        photo        : "./assets/img/projects/avila-mood.png",
        title        : "Sistema de Inventario",
        skill        : ["HTML", "CSS", "JavaScript", "Bootstrap", "JQuery", "Django"],
        description  : "Sistema de registro de productos diseñado para un centro estético. Desarrollado con los frameworks Django y Bootstrap, con el soporte de Sweetalert2 para la generación de alertas y Datatable para la visualización de tablas. Diseño Responsivo",
        date_project : "01/06/2023",
        observation  : "Cliente: Ávila Mood",
        link_github  : "https://github.com/roraima1986/software_peluqueria.github.io",
        link_website : "",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :6,
        photo        : "./assets/img/projects/panel-control-design.jpg",
        title        : "Sistema de Control de Pagos",
        skill        : ["HTML", "CSS", "JavaScript", "Bootstrap", "JQuery", "Django"],
        description  : "Sistema de registro y control de pagos de los clientes de la plataforma OPTICACLOUD. Desarrollado con los frameworks Django y Bootstrap, e integrando Sweetalert2 para la generación de alertas y Datatable para una visualización eficiente de tablas.",
        date_project : "01/03/2023",
        observation  : "Cliente: OPTICACLOUD",
        link_github  : "https://github.com/roraima1986/clientesOpticacloud",
        link_website : "",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :5,
        photo        : "./assets/img/projects/optiaustral-website-design.jpg",
        title        : "Página Web OptiAustral",
        skill        : ["HTML", "CSS", "Bootstrap", "JQuery"],
        description  : "Página web estática para una óptica, desarrollada utilizando el framework Bootstrap para garantizar un diseño responsivo y adaptable a diferentes dispositivos.",
        date_project : "01/10/2022",
        observation  : "Cliente: OptiAustral",
        link_github  : "https://github.com/roraima1986/optiaustral.github.io",
        link_website : "http://optiaustral.cl/",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :4,
        photo        : "./assets/img/projects/maqueta-css-flexbox-design.jpg",
        title        : "Maqueta CSS - Flexbox",
        skill        : ["HTML5", "CSS3"],
        description  : "Maquetación web de práctica diseñada para exhibir habilidades en animaciones utilizando CSS.",
        date_project : "22/10/2022",
        observation  : "Master CSS",
        link_github  : "https://github.com/roraima1986/cssflexbox.github.io",
        link_website : "https://roraima1986.github.io/cssflexbox.github.io/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :3,
        photo        : "./assets/img/projects/animaciones-css-design.jpg",
        title        : "Animaciones CSS",
        skill        : ["HTML", "CSS"],
        description  : "Maquetación web de practica para mostrar habilidades en animaciones con CSS.",
        date_project : "10/08/2022",
        observation  : "Master CSS",
        link_github  : "https://github.com/roraima1986/cssanimations.github.io",
        link_website : "https://roraima1986.github.io/cssanimations.github.io/",
        is_active    : true,
        is_destacad  : true,
      },
      {
        id           :2,
        photo        : "./assets/img/projects/jjingenieria-website-design.jpg",
        title        : "Página Web JJIngeniería",
        skill        : ["HTML", "CSS", "Bootstrap", "JQuery"],
        description  : "",
        date_project : "01/04/2021",
        observation  : "",
        link_github  : "https://github.com/roraima1986/jjingenieria.github.io",
        link_website : "https://jjingenieria.cl/",
        is_active    : false,
        is_destacad  : false,
      },
      {
        id           :1,
        photo        : "./assets/img/projects/opticacloud-website-design.jpg",
        title        : "Página Web OPTICACLOUD",
        skill        : ["HTML", "CSS", "Bootstrap", "JQuery"],
        description  : "Página web estática diseñada para presentar información sobre OPTICACLOUD, un software especializado en ópticas. Desarrollada utilizando el framework Bootstrap para asegurar un diseño responsivo y adaptable a diversos dispositivos.",
        date_project : "01/03/2021",
        observation  : "Cliente: OPTICACLOUD",
        link_github  : "https://github.com/roraima1986/opticacloud.github.io",
        link_website : "https://roraima1986.github.io/opticacloud.github.io/",
        is_active    : true,
        is_destacad  : true,
      },
    ]
  }

  getportfolioMini() {
    return Promise.resolve(this.getPortfolio());
  }
}
